# Generated by Django 5.2.16 on 2026-09-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='subject'),
        ),
    ]
