# Generated by Django 5.2.16 on 2026-09-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
