# Generated by Django 5.2.16 on 2026-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('domestic_flight', 'پرواز داخلی'), ('international_flight', 'پرواز خارجی'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('hotel', 'هتل'), ('villa', 'ویلا'), ('general', 'عمومی')], db_index=True, default='domestic_flight', max_length=30, verbose_name='دسته\u200cبندی')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['category', 'display_order', 'id'],
            },
        ),
    ]
