# Generated by Django 5.2.16 on 2026-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'id'], 'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('domestic_flight', 'پرواز داخلی'), ('international_flight', 'پرواز خارجی'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('hotel', 'هتل'), ('villa', 'ویلا'), ('general', 'عمومی')], db_index=True, default='domestic_flight', max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='answer'),
        ),
    ]
