# Generated by Django 5.2.16 on 2026-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0002_alter_faq_options_remove_faq_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('domestic_flight', 'Domestic Flight'), ('international_flight', 'International Flight'), ('train', 'Train'), ('bus', 'Bus'), ('hotel', 'Hotel'), ('villa', 'Villa'), ('tour', 'Tour'), ('general', 'General')], db_index=True, default='domestic_flight', max_length=30, verbose_name='category'),
        ),
    ]
