# Generated by Django 5.2.16 on 2026-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0003_alter_faq_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'display_order', 'id'], 'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
        migrations.AddField(
            model_name='faq',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='display_order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('domestic_flight', 'Domestic Flight'), ('international_flight', 'International Flight'), ('train', 'Train'), ('bus', 'Bus'), ('hotel', 'Hotel'), ('villa', 'Villa'), ('tour', 'Tour'), ('general', 'General')], db_index=True, default='domestic_flight', max_length=30, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='question'),
        ),
    ]
