# Generated by Django 5.2.16 on 2026-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0004_alter_faq_options_faq_display_order_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('domestic_flight', 'Domestic Flight'), ('international_flight', 'International Flight'), ('train', 'Train'), ('bus', 'Bus'), ('hotel', 'Hotel'), ('villa', 'Villa'), ('tour', 'Tour'), ('general', 'General')], db_index=True, default='domestic_flight', max_length=30, verbose_name='category')),
                ('name', models.CharField(max_length=100, verbose_name='Destination Name')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display_order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
