# Generated by Django 5.2.16 on 2026-09-09 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0006_alter_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='answer'),
        ),
    ]
