# Generated by Django 5.2.16 on 2026-09-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0007_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_domestic',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Domestic'),
        ),
    ]
