# Generated by Django 5.2.16 on 2026-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0008_destination_is_domestic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('hotel', 'Hotel'), ('villa', 'Villa'), ('tour', 'Tour'), ('general', 'General')], db_index=True, default='flight', max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('hotel', 'Hotel'), ('villa', 'Villa'), ('tour', 'Tour'), ('general', 'General')], db_index=True, default='flight', max_length=30, verbose_name='Category'),
        ),
    ]
